name: coverage

# Runs tests with coverage and reports the results

on: 
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-07-31
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
      - uses: actions-rs/grcov@v0.1
        with:
          config: $GITHUB_WORKSPACE/grcov.yml
      - uses: codecov/codecov-action@v2
        with:
          files: ./pointercrate.lcov
